In [1]:
import numpy as np

# Create a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, size=15)

# Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)

# Print array shape
print("Shape of the array:", reshaped_array.shape)

# Replace the max in each row by 0
reshaped_array[np.arange(len(reshaped_array)), np.argmax(reshaped_array, axis=1)] = 0

print("Array after replacing max in each row by 0:")
print(reshaped_array)

# Create a 2-dimensional array of size 4 x 3 with 4-byte integer elements
array_4x3 = np.zeros((4, 3), dtype=np.int32)

# Print shape, type, and data type of the array
print("Shape of the array_4x3:", array_4x3.shape)
print("Type of the array_4x3:", type(array_4x3))
print("Data type of the array_4x3:", array_4x3.dtype)


Shape of the array: (3, 5)
Array after replacing max in each row by 0:
[[ 0  7 12  5 15]
 [11  7 11 10  0]
 [16 12 11  1  0]]
Shape of the array_4x3: (4, 3)
Type of the array_4x3: <class 'numpy.ndarray'>
Data type of the array_4x3: int32


In [2]:
import numpy as np

# Given square array
square_array = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

# Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(square_array)

# Print eigenvalues and right eigenvectors
print("Eigenvalues:")
print(eigenvalues)
print("\nRight Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

Right Eigenvectors:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [3]:
import numpy as np

# Given array
given_array = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

# Compute the sum of diagonal elements
diagonal_sum = np.trace(given_array)

# Print the sum
print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 15


In [4]:
import numpy as np

# Given array
original_array = np.array([[1, 2],
                           [3, 4],
                           [5, 6]])

# Reshape to 3x2
reshaped_3x2 = np.reshape(original_array, (3, 2))

# Reshape to 2x3
reshaped_2x3 = np.reshape(original_array, (2, 3))

# Print the reshaped arrays
print("Reshaped to 3x2:")
print(reshaped_3x2)
print("\nReshaped to 2x3:")
print(reshaped_2x3)


Reshaped to 3x2:
[[1 2]
 [3 4]
 [5 6]]

Reshaped to 2x3:
[[1 2 3]
 [4 5 6]]
